import 'package:ainotes/app/common/constants/image_constants.dart';

List aiTools = [
  {
    "Category": "Website",
    "SubCategory": [
      {
        "id": 1,
        "Title": "About us",
        "Info":
            "Generate about us text on the title and description of a page.",
        "image": AiToolsIcons.aboutUsIcon,
        "prompt":
            "Generate in the :language language, an about us text, for a product named: :product. The voice tone is: :tone. The product is about: :description.",
        "language": true,
        "product": true,
        "tone": true,
        "description": true,
        "keywords": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 2,
        "Title": "Call to action",
        "Info":
            "Generate CTA lines based on the name and description of a product or service.",
        "image": AiToolsIcons.callToActionIcon,
        "prompt":
            "Generate in the :language language, a short CTA line for a product named: :product. The product is about: :description. The voice tone is: :tone.",
        "language": true,
        "product": true,
        "tone": true,
        "description": true,
        "keywords": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 3,
        "Title": "FAQ ",
        "Info": "Generate frequently asked questions for a product or service.",
        "image": AiToolsIcons.kFAQIcon,
        "prompt":
            "Generate in the :language language, a FAQ for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "keywords": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 4,
        "Title": "Hashtags",
        "Info": "Generate #hashtags for social network content.",
        "image": AiToolsIcons.hashTagIcon,
        "prompt":
            "Generate in the :language language, hashtags for: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "keywords": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 5,
        "Title": "How it works",
        "Info": "Generate steps about how a product or service works.",
        "image": AiToolsIcons.howItWorkIcon,
        "prompt":
            "Generate in the :language language, how it works steps, for a product named: :product. The product is about: :description.",
        "language": true,
        "description": true,
        "product": true,
        "tone": false,
        "keywords": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 6,
        "Title": "Meta description",
        "image": AiToolsIcons.metaDescriptionIcon,
        "Info":
            "Generate meta descriptions based on the title and description of a page.",
        "prompt":
            "Generate in the :language language, a description in two sentences, for a page called :name. Include the keywords: :keywords. The page is about: :description.",
        "language": true,
        "description": true,
        "name": true,
        "keywords": true,
        "product": false,
        "tone": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 7,
        "Title": "Meta keywords",
        "Info":
            "Generate meta keywords based on the title and description of a page.",
        "image": AiToolsIcons.metaKeyWord,
        "prompt":
            "Generate in the :language language, meta keywords for a page called :name. The page is about: :description.",
        "language": true,
        "description": true,
        "name": true,
        "keywords": false,
        "product": false,
        "tone": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 8,
        "Title": "Subheadline",
        "Info": "Generate engaging subheadlines for products and services.",
        "image": AiToolsIcons.subHeadingIcon,
        "prompt":
            "Generate in the :language language, a subheadline for a product named: :product. The product is about: :description. The voice tone is: :tone.",
        "language": true,
        "product": true,
        "description": true,
        "tone": true,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 9,
        "Title": "Testimonial",
        "Info":
            "Generate testimonials based on the name and description of a product or service.",
        "image": AiToolsIcons.testimonial,
        "prompt":
            "Generate in the :language language, a testimonial of about 25 words for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 10,
        "Title": "Pros and cons",
        "Info": "Generate pros and cons for a product or service.",
        "image": AiToolsIcons.prosAndConsIcon,
        "prompt":
            "Generate in the :language language, pros and cons for a product named: :product. The product is about: :description",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 11,
        "Title": "Review ",
        "Info":
            "Generate reviews based on the name and description of a product or service.",
        "image": AiToolsIcons.reviewIcon,
        "prompt":
            "Generate in the :language language, a review for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 12,
        "Title": "Feature section",
        "Info": "Generate feature sections to highlight a product or service.",
        "image": AiToolsIcons.featureSection,
        "prompt":
            "Generate in the :language language, a feature section for the :title title. The voice tone is: :tone. The product is named: :product. The product is about: :description.",
        "language": true,
        "title": true,
        "tone": true,
        "product": true,
        "description": true,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
    ],
  },
  {
    "Category": "Marketing",
    "SubCategory": [
      {
        "id": 1,
        "Title": "Advertisement",
        "Info": "Generate creative ad descriptions for a product or service.",
        "image": AiToolsIcons.advertisementIcon,
        "prompt":
            "Generate in the :language language, for the product: :product.",
        "language": true,
        "product": true,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 2,
        "Title": "Mission statement",
        "Info": "Generate comprehensive and informative mission statements.",
        "image": AiToolsIcons.missionStatementIcon,
        "prompt":
            "Generate in the :language language, a mission statement for the company: :company. The voice tone is: :tone. The company is about :description.",
        "language": true,
        "tone": true,
        "company": true,
        "description": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 3,
        "Title": "Newsletter",
        "Info": "Generate engaging and comprehensive newsletters.",
        "image": AiToolsIcons.newsLetterIcon,
        "prompt":
            "Generate in the :language language, a newsletter with the subject: :subject. The company is: :company. The voice tone is: :tone.",
        "language": true,
        "tone": true,
        "subject": true,
        "company": true,
        "product": false,
        "description": false,
        "name": false,
        "keywords": false,
        "title": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 4,
        "Title": "Pain-Agitate-Solution",
        "Info": "Generate high-converting sales copy using the PAS formula.",
        "image": AiToolsIcons.painAgitateSolutionIcon,
        "prompt":
            "Generate in the :language language, a Pain-Agitate-Solution for a product called :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 5,
        "Title": "Press release",
        "Info": "Generate comprehensive and informative press releases.",
        "image": AiToolsIcons.pressReleaseIcon,
        "prompt":
            "Generate in the :language language, a press release for the company: :company. The voice tone is: :tone. The company is about :description. The press release subject is about: :subject.",
        "language": true,
        "company": true,
        "tone": true,
        "description": true,
        "subject": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 6,
        "Title": "Startup ideas",
        "Info": "Generate innovative startup ideas based on domains.",
        "image": AiToolsIcons.startUpIdeaIcon,
        "prompt":
            "Generate in the :language language, startup ideas in the folloing domains: :domains.",
        "language": true,
        "domains": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "content": false,
      },
      {
        "id": 7,
        "Title": "Startup names",
        "image": AiToolsIcons.startUpNameIcon,
        "Info":
            "Generate creative startup names based on the description and keywords.",
        "prompt":
            "Generate in the :language language, a list of startup names that include any of the keywords: :keywords. The startup is about: :description.",
        "language": true,
        "keywords": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 8,
        "Title": "Value proposition",
        "Info": "Generate value propositions for a product or service.",
        "image": AiToolsIcons.valueProposition,
        "prompt":
            "Generate in the :language language, a value proposition for the product: :product. The voice tone is: :tone. The company is about :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": true,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 9,
        "Title": "Vision statement",
        "Info": "Generate comprehensive and informative vision statements.",
        "image": AiToolsIcons.visionStatementIcon,
        "prompt":
            "Generate in the :language language, a vision statement for the company: :company. The voice tone is: :tone. The company is about :description",
        "language": true,
        "company": true,
        "tone": true,
        "description": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 10,
        "Title": "Product sheet",
        "Info": "Generate compelling product sheets for a product or service.",
        "image": AiToolsIcons.productSheetIcon,
        "prompt":
            "Generate in the :language language, a product sheet for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 11,
        "Title": "Welcome email",
        "Info": "Generate engaging welcome emails for a product or service.",
        "image": AiToolsIcons.welComeEmailIcon,
        "prompt":
            "Generate in the :language language, a welcome email for a product named: :product. The voice tone is: :tone. The product is about: :description.",
        "language": true,
        "product": true,
        "tone": true,
        "description": true,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 12,
        "Title": "Push notification",
        "Info":
            "Generate push notifications based on the description of a product or service.",
        "image": AiToolsIcons.pushNotificationIcon,
        "prompt":
            "Generate in the :language language, a push notification with a maximum of 160 characters, for a product about: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 13,
        "Title": "Google advertisement",
        "Info":
            "Generate optimized Google advertisements for a product or service.",
        "image": AiToolsIcons.googleAdsIcon,
        "prompt":
            "Generate in the :language language, an ad with 3 Headlines of maximum 30 characters each, and 2 Descriptions of maximum 90 characters each, for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 14,
        "Title": "Facebook advertisement",
        "Info":
            "Generate optimized Facebook advertisements for a product or service.",
        "image": AiToolsIcons.facebookAdsIcon,
        "prompt":
            "Generate in the :language language, an ad with a Headline of maximum 27 characters, a Description of maximum 27 characters, and a short Primary Text must not exceed 127 characters, for a product named: :product. The product is about: :description.",
        "language": true,
        "product": true,
        "description": true,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 15,
        "Title": "Job description",
        "Info":
            "Generate professional job descriptions to attract top talents.",
        "image": AiToolsIcons.jobDescriptionIcon,
        "prompt":
            "Generate in the :language language, a job description for a :position position, at a company called: :company. The company is about: :description.",
        "language": true,
        "description": true,
        "company": true,
        "position": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "subject": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
    ],
  },
  {
    "Category": "Content",
    "SubCategory": [
      {
        "id": 1,
        "Title": "Article ",
        "Info": "Generate articles based on title, keywords, and subheading.",
        "image": AiToolsIcons.articleIcon,
        "prompt":
            "Generate in the :language language, an article about :title. The topics of the articles are: :subheadings. Include the keywords: :keywords. The length of the article should be: :length.",
        "language": true,
        "subheadings": true,
        "keywords": true,
        "length": true,
        "title": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "company": false,
        "subject": false,
        "position": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 2,
        "Title": "Blog intro",
        "Info":
            "Generate blog intros based on the blog post title and content.",
        "image": AiToolsIcons.blogIntroIcon,
        "prompt":
            "Generate in the :language language, an intro for a blog post titled: :title. The blog post is about: :content.",
        "language": true,
        "title": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 3,
        "Title": "Blog outline",
        "Info":
            "Generate blog outlines based on the blog post title and content.",
        "image": AiToolsIcons.blogOutlineIcon,
        "prompt":
            "Generate in the :language language, an outline for a blog post titled: :title. The blog post is about: :content.",
        "language": true,
        "content": true,
        "title": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 4,
        "Title": "Blog outro",
        "Info":
            "Generate blog outros based on the blog post title and content.",
        "image": AiToolsIcons.blogOutroIcon,
        "prompt":
            "Generate in the :language language, an outro for a blog post titled: :title. The blog post is about: :content.",
        "language": true,
        "content": true,
        "title": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 5,
        "Title": "Blog paragraph",
        "Info":
            "Generate blog paragraphs based on the blog post title and subheading.",
        "image": AiToolsIcons.blogParagraphIcon,
        "prompt":
            "Generate in the :language language, a blog paragraph about :title. The topic of the paragraph is: :subheading.",
        "language": true,
        "title": true,
        "subheadings": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 6,
        "Title": "Blog post",
        "Info": "Generate blog posts, focused on keywords, about any topic.",
        "image": AiToolsIcons.blogPostIcon,
        "prompt":
            "Generate in the :language language, a blog post about: :description. Focus on the keywords: :keywords.",
        "language": true,
        "description": true,
        "keywords": true,
        "product": false,
        "tone": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 7,
        "Title": "Blog section",
        "Info":
            "Generate blog sections based on the blog post title and subheading.",
        "image": AiToolsIcons.blogSectionIcon,
        "prompt":
            "Generate in the :language language, a few blog paragraphs about :title. The topic of the paragraphs is: :subheading.",
        "language": true,
        "title": true,
        "subheadings": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 8,
        "Title": "Blog talking points",
        "Info":
            "Generate blog talking points based on the blog post title and subheading.",
        "image": AiToolsIcons.blogTalkingIcon,
        "prompt":
            "Generate in the :language language, talking points for a blog post titled: :title. The blog topic is: :subheading.",
        "language": true,
        "title": true,
        "subheadings": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 9,
        "Title": "Blog title",
        "Info": "Generate blog titles based on the blog post content.",
        "image": AiToolsIcons.startUpNameIcon,
        "prompt":
            "Generate in the :language language, a blog title where the content of the blog post is: :content.",
        "language": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 10,
        "Title": "Content rewrite",
        "image": AiToolsIcons.contentRewriteIcon,
        "Info": "Rewrite any kind of content in seconds, in an enhanced way.",
        "prompt": "Rewrite in the :language language: :content",
        "language": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 11,
        "Title": "Content summary",
        "image": AiToolsIcons.contentSummaryIcon,
        "Info": "Summarize any kind of content in seconds, in an enhanced way.",
        "prompt": "Summarize in the :language language: :content",
        "language": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 12,
        "Title": "Paragraph ",
        "Info": "Generate paragraphs, focused on keywords, about any topic.",
        "image": AiToolsIcons.paragraphIcon,
        "prompt":
            "Generate in the :language language, a paragraph about :description. Include the keywords: :keywords.",
        "language": true,
        "description": true,
        "keywords": true,
        "product": false,
        "tone": false,
        "name": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 13,
        "Title": "Blog listicle",
        "image": AiToolsIcons.blogListicleIcon,
        "Info":
            "Generate blog listicles based on the blog post title and content",
        "prompt":
            "Generate in the :language language, a listicle for a blog post titled: :title. The blog post is about: :content.",
        "language": true,
        "title": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 14,
        "Title": "Content grammar",
        "image": AiToolsIcons.contentGrammerIcon,
        "Info": "Correct the grammatical errors for any text in seconds.",
        "prompt":
            "Correct in the :language language, the grammatical errors for the following text: :content",
        "language": true,
        "content": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
      {
        "id": 15,
        "Title": "Blog tags",
        "image": AiToolsIcons.blogTagsIcon,
        "Info": "Generate blog tags based on the blog post title and content.",
        "prompt":
            "Generate in the :language language, tags separated by comma, for a blog post titled: :title. The blog post is about: :content.",
        "language": true,
        "content": true,
        "title": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
      },
    ],
  },
  {
    "Category": "Social",
    "SubCategory": [
      {
        "id": 1,
        "Title": "Hashtags ",
        "Info": "Generate #hashtags for social network content.",
        "image": AiToolsIcons.hashTagIcon,
        "prompt":
            "Generate in the :language language, hashtags for: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 2,
        "Title": "Social post",
        "Info":
            "Generate social posts ready to be published on social platforms.",
        "image": AiToolsIcons.socialPostIcon,
        "prompt":
            "Generate in the :language language, a social post about: :description. The voice tone is: :tone.",
        "language": true,
        "tone": true,
        "description": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 3,
        "Title": "Social post caption",
        "Info": "Generate social post captions ready to grab attention.",
        "image": AiToolsIcons.socialPostCaptionIcon,
        "prompt":
            "Generate in the :language language, a social post caption about: :description. The voice tone is: :tone.",
        "language": true,
        "description": true,
        "tone": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 4,
        "Title": "Tweet",
        "Info": "Generate engaging tweets based on a description.",
        "image": AiToolsIcons.tweetIcon,
        "prompt":
            "Generate in the :language language, a tweet about: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 5,
        "Title": "Twitter thread",
        "Info": "Generate engaging twitter threads based on a description.",
        "image": AiToolsIcons.twitterThread,
        "prompt":
            "Generate in the :language language, a twitter thread about: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 6,
        "Title": "Video description",
        "Info":
            "Generate compelling video descriptions based on a description.",
        "image": AiToolsIcons.videoDescriptionIcon,
        "prompt":
            "Generate in the :language language, a video description about: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 7,
        "Title": "Video script",
        "Info": "Generate detailed video scripts based on a description.",
        "image": AiToolsIcons.videoScriptIcon,
        "prompt":
            "Generate in the :language language, a video script for a video about: :description. The voice tone is: :tone.",
        "language": true,
        "tone": true,
        "description": true,
        "product": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 8,
        "Title": "Video tags",
        "Info": "Generate video tags for videos based on the video title.",
        "image": AiToolsIcons.videoTagsIcon,
        "prompt":
            "Generate in the :language language, tags separated by comma, for the video called: :title.",
        "language": true,
        "title": true,
        "product": false,
        "description": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
      {
        "id": 9,
        "Title": "Video title",
        "image": AiToolsIcons.startUpNameIcon,
        "Info":
            "Generate engaging video titles based on the video description.",
        "prompt":
            "Generate in the :language language, a video title about: :description.",
        "language": true,
        "description": true,
        "product": false,
        "tone": false,
        "name": false,
        "keywords": false,
        "title": false,
        "company": false,
        "subject": false,
        "position": false,
        "subheadings": false,
        "length": false,
        "domains": false,
        "content": false,
      },
    ],
  },
];

/// --------------------------
// List aiTools = [
//   {
//     "Category": "Website",
//     "SubCategory": [
//       {
//         "id": 1,
//         "Title": "About us",
//         "Info":
//             "Generate about us text on the title and description of a page.",
//         "prompt":
//             "Generate in the :language language, an about us text, for a product named: :product. The voice tone is: :tone. The audience is: :audience. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "tone": true,
//         "audience": true,
//         "description": true,
//         "keywords": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 2,
//         "Title": "Call to action",
//         "Info":
//             "Generate CTA lines based on the name and description of a product or service.",
//         "prompt":
//             "Generate in the :language language, a short CTA line for a product named: :product. The product is about: :description. The audience of the product will include: :audience. The voice tone is: :tone.",
//         "language": true,
//         "product": true,
//         "tone": true,
//         "audience": true,
//         "description": true,
//         "keywords": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 3,
//         "Title": "FAQ ",
//         "Info": "Generate frequently asked questions for a product or service.",
//         "prompt":
//             "Generate in the :language language, a FAQ for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "tone": false,
//         "audience": false,
//         "keywords": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 4,
//         "Title": "Hashtags",
//         "Info": "Generate #hashtags for social network content.",
//         "prompt":
//             "Generate in the :language language, hashtags for: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "tone": false,
//         "audience": false,
//         "keywords": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 5,
//         "Title": "How it works",
//         "Info": "Generate steps about how a product or service works.",
//         "prompt":
//             "Generate in the :language language, how it works steps, for a product named: :product. The audience is: :audience. The product is about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "tone": false,
//         "audience": false,
//         "keywords": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 6,
//         "Title": "Meta description",
//         "Info":
//             "Generate meta descriptions based on the title and description of a page.",
//         "prompt":
//             "Generate in the :language language, a description in two sentences, for a page called :name. Include the keywords: :keywords. The page is about: :description.",
//         "language": true,
//         "description": true,
//         "name": true,
//         "keywords": true,
//         "product": false,
//         "tone": false,
//         "audience": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 7,
//         "Title": "Meta keywords",
//         "Info":
//             "Generate meta keywords based on the title and description of a page.",
//         "prompt":
//             "Generate in the :language language, meta keywords for a page called :name. The page is about: :description.",
//         "language": true,
//         "description": true,
//         "name": true,
//         "keywords": false,
//         "product": false,
//         "tone": false,
//         "audience": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 8,
//         "Title": "Subheadline",
//         "Info": "Generate engaging subheadlines for products and services.",
//         "prompt":
//             "Generate in the :language language, a subheadline for a product named: :product. The product is about: :description. The audience of the product will include: :audience. The voice tone is: :tone.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": true,
//         "tone": true,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 9,
//         "Title": "Testimonial",
//         "Info":
//             "Generate testimonials based on the name and description of a product or service.",
//         "prompt":
//             "Generate in the :language language, a testimonial of about 25 words for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 10,
//         "Title": "Pros and cons",
//         "Info": "Generate pros and cons for a product or service.",
//         "prompt":
//             "Generate in the :language language, pros and cons for a product named: :product. The product is about: :description",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 11,
//         "Title": "Review ",
//         "Info":
//             "Generate reviews based on the name and description of a product or service.",
//         "prompt":
//             "Generate in the :language language, a review for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 12,
//         "Title": "Feature section",
//         "Info": "Generate feature sections to highlight a product or service.",
//         "prompt":
//             "Generate in the :language language, a feature section for the :title title. The audience is: :audience. The voice tone is: :tone. The product is named: :product. The product is about: :description.",
//         "language": true,
//         "title": true,
//         "audience": true,
//         "tone": true,
//         "product": true,
//         "description": true,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//     ],
//   },
//   {
//     "Category": "Marketing",
//     "SubCategory": [
//       {
//         "id": 1,
//         "Title": "Advertisement",
//         "Info": "Generate creative ad descriptions for a product or service.",
//         "prompt":
//             "Generate in the :language language, a creative ad, aimed at: :audience, for the product: :product.",
//         "language": true,
//         "product": true,
//         "audience": true,
//         "description": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 2,
//         "Title": "Mission statement",
//         "Info": "Generate comprehensive and informative mission statements.",
//         "prompt":
//             "Generate in the :language language, a mission statement for the company: :company. The voice tone is: :tone. The company is about :description.",
//         "language": true,
//         "tone": true,
//         "company": true,
//         "description": true,
//         "audience": false,
//         "product": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 3,
//         "Title": "Newsletter",
//         "Info": "Generate engaging and comprehensive newsletters.",
//         "prompt":
//             "Generate in the :language language, a newsletter with the subject: :subject. The company is: :company. The voice tone is: :tone.",
//         "language": true,
//         "tone": true,
//         "subject": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 4,
//         "Title": "Pain-Agitate-Solution",
//         "Info": "Generate high-converting sales copy using the PAS formula.",
//         "prompt":
//             "Generate in the :language language, a Pain-Agitate-Solution for a product called :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 5,
//         "Title": "Press release",
//         "Info": "Generate comprehensive and informative press releases.",
//         "prompt":
//             "Generate in the :language language, a press release for the company: :company. The voice tone is: :tone. The company is about :description. The press release subject is about: :subject.",
//         "language": true,
//         "company": true,
//         "tone": true,
//         "description": true,
//         "subject": true,
//         "product": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 6,
//         "Title": "Startup ideas",
//         "Info": "Generate innovative startup ideas based on domains.",
//         "prompt":
//             "Generate in the :language language, startup ideas in the folloing domains: :domains.",
//         "language": true,
//         "domains": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "content": false,
//       },
//       {
//         "id": 7,
//         "Title": "Startup names",
//         "Info":
//             "Generate creative startup names based on the description and keywords.",
//         "prompt":
//             "Generate in the :language language, a list of startup names that include any of the keywords: :keywords. The startup is about: :description.",
//         "language": true,
//         "keywords": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 8,
//         "Title": "Value proposition",
//         "Info": "Generate value propositions for a product or service.",
//         "prompt":
//             "Generate in the :language language, a value proposition for the product: :product. The audience is: :audience. The voice tone is: :tone. The company is about :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": true,
//         "tone": true,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 9,
//         "Title": "Vision statement",
//         "Info": "Generate comprehensive and informative vision statements.",
//         "prompt":
//             "Generate in the :language language, a vision statement for the company: :company. The voice tone is: :tone. The company is about :description",
//         "language": true,
//         "company": true,
//         "tone": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 10,
//         "Title": "Product sheet",
//         "Info": "Generate compelling product sheets for a product or service.",
//         "prompt":
//             "Generate in the :language language, a product sheet for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 11,
//         "Title": "Welcome email",
//         "Info": "Generate engaging welcome emails for a product or service.",
//         "prompt":
//             "Generate in the :language language, a welcome email for a product named: :product. The voice tone is: :tone. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "tone": true,
//         "description": true,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 12,
//         "Title": "Push notification",
//         "Info":
//             "Generate push notifications based on the description of a product or service.",
//         "prompt":
//             "Generate in the :language language, a push notification with a maximum of 160 characters, for a product about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 13,
//         "Title": "Google advertisement",
//         "Info":
//             "Generate optimized Google advertisements for a product or service.",
//         "prompt":
//             "Generate in the :language language, an ad with 3 Headlines of maximum 30 characters each, and 2 Descriptions of maximum 90 characters each, for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 14,
//         "Title": "Facebook advertisement",
//         "Info":
//             "Generate optimized Facebook advertisements for a product or service.",
//         "prompt":
//             "Generate in the :language language, an ad with a Headline of maximum 27 characters, a Description of maximum 27 characters, and a short Primary Text must not exceed 127 characters, for a product named: :product. The product is about: :description.",
//         "language": true,
//         "product": true,
//         "description": true,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 15,
//         "Title": "Job description",
//         "Info":
//             "Generate professional job descriptions to attract top talents.",
//         "prompt":
//             "Generate in the :language language, a job description for a :position position, at a company called: :company. The company is about: :description.",
//         "language": true,
//         "description": true,
//         "company": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//     ],
//   },
//   {
//     "Category": "Content",
//     "SubCategory": [
//       {
//         "id": 1,
//         "Title": "Article ",
//         "Info": "Generate articles based on title, keywords, and subheading.",
//         "prompt":
//             "Generate in the :language language, an article about :title. The topics of the articles are: :subheadings. Include the keywords: :keywords. The length of the article should be: :length.",
//         "language": true,
//         "subheadings": true,
//         "keywords": true,
//         "length": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 2,
//         "Title": "Blog intro",
//         "Info":
//             "Generate blog intros based on the blog post title and content.",
//         "prompt":
//             "Generate in the :language language, an intro for a blog post titled: :title. The blog post is about: :content.",
//         "language": true,
//         "title": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 3,
//         "Title": "Blog outline",
//         "Info":
//             "Generate blog outlines based on the blog post title and content.",
//         "prompt":
//             "Generate in the :language language, an outline for a blog post titled: :title. The blog post is about: :content.",
//         "language": true,
//         "content": true,
//         "title": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 4,
//         "Title": "Blog outro",
//         "Info":
//             "Generate blog outros based on the blog post title and content.",
//         "prompt":
//             "Generate in the :language language, an outro for a blog post titled: :title. The blog post is about: :content.",
//         "language": true,
//         "content": true,
//         "title": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 5,
//         "Title": "Blog paragraph",
//         "Info":
//             "Generate blog paragraphs based on the blog post title and subheading.",
//         "prompt":
//             "Generate in the :language language, a blog paragraph about :title. The topic of the paragraph is: :subheading.",
//         "language": true,
//         "title": true,
//         "subheadings": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 6,
//         "Title": "Blog post",
//         "Info": "Generate blog posts, focused on keywords, about any topic.",
//         "prompt":
//             "Generate in the :language language, a blog post about: :description. Focus on the keywords: :keywords.",
//         "language": true,
//         "description": true,
//         "keywords": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 7,
//         "Title": "Blog section",
//         "Info":
//             "Generate blog sections based on the blog post title and subheading.",
//         "prompt":
//             "Generate in the :language language, a few blog paragraphs about :title. The topic of the paragraphs is: :subheading.",
//         "language": true,
//         "title": true,
//         "subheadings": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 8,
//         "Title": "Blog talking points",
//         "Info":
//             "Generate blog talking points based on the blog post title and subheading.",
//         "prompt":
//             "Generate in the :language language, talking points for a blog post titled: :title. The blog topic is: :subheading.",
//         "language": true,
//         "title": true,
//         "subheadings": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 9,
//         "Title": "Blog title",
//         "Info": "Generate blog titles based on the blog post content.",
//         "prompt":
//             "Generate in the :language language, a blog title where the content of the blog post is: :content.",
//         "language": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 10,
//         "Title": "Content rewrite",
//         "Info": "Rewrite any kind of content in seconds, in an enhanced way.",
//         "prompt": "Rewrite in the :language language: :content",
//         "language": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 11,
//         "Title": "Content summary",
//         "Info": "Summarize any kind of content in seconds, in an enhanced way.",
//         "prompt": "Summarize in the :language language: :content",
//         "language": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 12,
//         "Title": "Paragraph ",
//         "Info": "Generate paragraphs, focused on keywords, about any topic.",
//         "prompt":
//             "Generate in the :language language, a paragraph about :description. Include the keywords: :keywords.",
//         "language": true,
//         "description": true,
//         "keywords": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 13,
//         "Title": "Blog listicle",
//         "Info":
//             "Generate blog listicles based on the blog post title and content",
//         "prompt":
//             "Generate in the :language language, a listicle for a blog post titled: :title. The blog post is about: :content.",
//         "language": true,
//         "title": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 14,
//         "Title": "Content grammar",
//         "Info": "Correct the grammatical errors for any text in seconds.",
//         "prompt":
//             "Correct in the :language language, the grammatical errors for the following text: :content",
//         "language": true,
//         "content": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//       {
//         "id": 15,
//         "Title": "Blog tags",
//         "Info": "Generate blog tags based on the blog post title and content.",
//         "prompt":
//             "Generate in the :language language, tags separated by comma, for a blog post titled: :title. The blog post is about: :content.",
//         "language": true,
//         "content": true,
//         "title": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//       },
//     ],
//   },
//   {
//     "Category": "Social",
//     "SubCategory": [
//       {
//         "id": 1,
//         "Title": "Hashtags ",
//         "Info": "Generate #hashtags for social network content.",
//         "prompt":
//             "Generate in the :language language, hashtags for: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 2,
//         "Title": "Social post",
//         "Info":
//             "Generate social posts ready to be published on social platforms.",
//         "prompt":
//             "Generate in the :language language, a social post about: :description. The voice tone is: :tone.",
//         "language": true,
//         "tone": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 3,
//         "Title": "Social post caption",
//         "Info": "Generate social post captions ready to grab attention.",
//         "prompt":
//             "Generate in the :language language, a social post caption about: :description. The voice tone is: :tone.",
//         "language": true,
//         "description": true,
//         "tone": true,
//         "product": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 4,
//         "Title": "Tweet",
//         "Info": "Generate engaging tweets based on a description.",
//         "prompt":
//             "Generate in the :language language, a tweet about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 5,
//         "Title": "Twitter thread",
//         "Info": "Generate engaging twitter threads based on a description.",
//         "prompt":
//             "Generate in the :language language, a twitter thread about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 6,
//         "Title": "Video description",
//         "Info":
//             "Generate compelling video descriptions based on a description.",
//         "prompt":
//             "Generate in the :language language, a video description about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 7,
//         "Title": "Video script",
//         "Info": "Generate detailed video scripts based on a description.",
//         "prompt":
//             "Generate in the :language language, a video script for a video about: :description. The voice tone is: :tone.",
//         "language": true,
//         "tone": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 8,
//         "Title": "Video tags",
//         "Info": "Generate video tags for videos based on the video title.",
//         "prompt":
//             "Generate in the :language language, tags separated by comma, for the video called: :title.",
//         "language": true,
//         "title": true,
//         "product": false,
//         "description": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//       {
//         "id": 9,
//         "Title": "Video title",
//         "Info":
//             "Generate engaging video titles based on the video description.",
//         "prompt":
//             "Generate in the :language language, a video title about: :description.",
//         "language": true,
//         "description": true,
//         "product": false,
//         "audience": false,
//         "tone": false,
//         "name": false,
//         "keywords": false,
//         "title": false,
//         "company": false,
//         "subject": false,
//         "position": false,
//         "subheadings": false,
//         "length": false,
//         "domains": false,
//         "content": false,
//       },
//     ],
//   },
// ];
