import 'package:flutter/material.dart';

/// Suggestion Text List
List askToChatGptQuestion = [
  "Can you tell me a joke?",
  "How many planets are in the solar system?",
  "Can you recommend a good book?",
  "What is the meaning of life?",
  "How many planets are in the solar system?",
];

/// Language List
List<DropdownMenuItem> items = [
  const DropdownMenuItem(value: "Afrikaans", child: Text("Afrikaans")),
  const DropdownMenuItem(value: "Albanian", child: Text("Albanian")),
  const DropdownMenuItem(value: "Arabic", child: Text("Arabic")),
  const DropdownMenuItem(value: "Belarusian", child: Text("Belarusian")),
  const DropdownMenuItem(value: "Bulgarian", child: Text("Bulgarian")),
  const DropdownMenuItem(value: "Bangla", child: Text("Bangla")),
  const DropdownMenuItem(value: "Catalan", child: Text("Catalan")),
  const DropdownMenuItem(value: "Chinese", child: Text("Chinese")),
  const DropdownMenuItem(value: "Croatian", child: Text("Croatian")),
  const DropdownMenuItem(value: "Czech", child: Text("Czech")),
  const DropdownMenuItem(value: "Danish", child: Text("Danish")),
  const DropdownMenuItem(value: "Dutch", child: Text("Dutch")),
  const DropdownMenuItem(value: "English", child: Text("English")),
  const DropdownMenuItem(value: "Esperanto", child: Text("Esperanto")),
  const DropdownMenuItem(value: "Estonian", child: Text("Estonian")),
  const DropdownMenuItem(value: "Finnish", child: Text("Finnish")),
  const DropdownMenuItem(value: "French", child: Text("French")),
  const DropdownMenuItem(value: "Galician", child: Text("Galician")),
  const DropdownMenuItem(value: "Georgian", child: Text("Georgian")),
  const DropdownMenuItem(value: "German", child: Text("German")),
  const DropdownMenuItem(value: "Greek", child: Text("Greek")),
  const DropdownMenuItem(value: "Gujarati", child: Text("Gujarati")),
  const DropdownMenuItem(value: "HaitianCreole", child: Text("HaitianCreole")),
  const DropdownMenuItem(value: "Hebrew", child: Text("Hebrew")),
  const DropdownMenuItem(value: "Hindi", child: Text("Hindi")),
  const DropdownMenuItem(value: "Hungarian", child: Text("Hungarian")),
  const DropdownMenuItem(value: "Icelandic", child: Text("Icelandic")),
  const DropdownMenuItem(value: "Indonesian", child: Text("Indonesian")),
  const DropdownMenuItem(value: "Irish", child: Text("Irish")),
  const DropdownMenuItem(value: "Italian", child: Text("Italian")),
  const DropdownMenuItem(value: "Japanese", child: Text("Japanese")),
  const DropdownMenuItem(value: "Kannada", child: Text("Kannada")),
  const DropdownMenuItem(value: "Korean", child: Text("Korean")),
  const DropdownMenuItem(value: "Lithuanian", child: Text("Lithuanian")),
  const DropdownMenuItem(value: "Latvian", child: Text("Latvian")),
  const DropdownMenuItem(value: "Macedonian", child: Text("Macedonian")),
  const DropdownMenuItem(value: "Marathi", child: Text("Marathi")),
  const DropdownMenuItem(value: "Malay", child: Text("Malay")),
  const DropdownMenuItem(value: "Maltese", child: Text("Maltese")),
  const DropdownMenuItem(value: "Norwegian", child: Text("Norwegian")),
  const DropdownMenuItem(value: "Persian", child: Text("Persian")),
  const DropdownMenuItem(value: "Polish", child: Text("Polish")),
  const DropdownMenuItem(value: "Portuguese", child: Text("Portuguese")),
  const DropdownMenuItem(value: "Romanian", child: Text("Romanian")),
  const DropdownMenuItem(value: "Russian", child: Text("Russian")),
  const DropdownMenuItem(value: "Slovak", child: Text("Slovak")),
  const DropdownMenuItem(value: "Slovenian", child: Text("Slovenian")),
  const DropdownMenuItem(value: "Spanish", child: Text("Spanish")),
  const DropdownMenuItem(value: "Swedish", child: Text("Swedish")),
  const DropdownMenuItem(value: "Swahili", child: Text("Swahili")),
  const DropdownMenuItem(value: "Tagalog", child: Text("Tagalog")),
  const DropdownMenuItem(value: "Tamil", child: Text("Tamil")),
  const DropdownMenuItem(value: "Telugu", child: Text("Telugu")),
  const DropdownMenuItem(value: "Thai", child: Text("Thai")),
  const DropdownMenuItem(value: "Turkish", child: Text("Turkish")),
  const DropdownMenuItem(value: "Ukrainian", child: Text("Ukrainian")),
  const DropdownMenuItem(value: "Urdu", child: Text("Urdu")),
  const DropdownMenuItem(value: "Vietnamese", child: Text("Vietnamese")),
  const DropdownMenuItem(value: "Welsh", child: Text("Welsh")),
];
